steps:
  - id: "Watch:slackbot"
    name: "gcr.io/$PROJECT_ID/slackbot"
    args:
      [
        "--build",
        "$BUILD_ID",
        "--webhook",
        "https://hooks.slack.com/services/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",
        "--copy-timeout",
      ]
  - id: "Install:npm_packages"
    name: node
    args: ["npm", "install"]
    dir: "src"
    waitFor: ["-"]
  - id: "Install:functions_npm_packages"
    name: node
    args: ["npm", "install"]
    dir: "functions"
    waitFor: ["-"]
  - id: "Fetch:dotenv"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud secrets versions access latest --secret=dotenv_file --format='get(payload.data)' --project $PROJECT_ID | tr '_-' '/+' | base64 -d > .env.production",
      ]
    dir: "src"
    waitFor: ["Watch:slackbot"]
  # - id: "Run:test"
  #   name: node
  #   args: ["npm", "run", "ci-test"]
  #   dir: "src"
  #   waitFor: ["Install:npm_packages", "Install:functions_npm_packages"]
  - id: "Build:App"
    # name: node
    name: node
    args: ["npm", "run", "build-next:${_FIREBASE_ENV}"]
    dir: "src"
  - id: "Deploy:Firebase"
    # name: node
    name: "gcr.io/$PROJECT_ID/maven-node-openjdk"
    args: ["npm", "run", "ci-deploy:${_FIREBASE_ENV}"]
    dir: "src"
timeout: 2500s
